version: "3.8"

services:
    backend:
        image: allchat-backend
        ports:
            - "6000:5000"
        environment:
            - NODE_ENV=production
            - GEMINI_KEY=${GEMINI_KEY}
            - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
            - AWS_SECRET_KEY=${AWS_SECRET_KEY}
            - CLAUDE_KEY=${CLAUDE_KEY}
            - STRIPE_KEY=${STRIPE_KEY}
            - STRIPE_WH_SECRET=${STRIPE_WH_SECRET}
            - JWT_TOKEN=${JWT_TOKEN}
            - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
            - YAHOO_FINANCE_API_KEY=${YAHOO_FINANCE_API_KEY}
            - TELEGRAM_KEY=${TELEGRAM_KEY}
            - EMAIL=${EMAIL}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - TOGETHER_KEY=${TOGETHER_KEY}
        restart: unless-stopped
        depends_on:
            - mongodb

    frontend:
        image: allchat-frontend
        environment:
            - NODE_ENV=production
        ports:
            - "8585:80"
        restart: unless-stopped
        depends_on:
            - backend

    mongodb:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        restart: unless-stopped
        logging:
            driver: none

    python-shell:
        image: python:3.12
        volumes:
            - ./python-scripts:/app
            - ./requirements.txt:/requirements.txt
        restart: unless-stopped
        working_dir: /app
        command: ["sh", "-c", "pip install --no-cache-dir -r /requirements.txt && python -u shell.py"]
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHON_SERVER_PORT=8000

volumes:
    mongo-data:
